[versions]
# 8.13.2 Before
agp = "8.10.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2024.09.00"
locationService = "21.3.0"
appCompat = "1.7.1"
roomVersion="2.8.4"
ksp = "2.0.21-1.0.25"
mapLibreSdk="12.3.1"
mapLibreAnotation="3.0.2"
androidxNavigation="2.9.7"
materialIconsExtended="1.7.8"
gradleSecrets="2.0.1"
coilCompose="2.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref="appCompat" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref="roomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref="roomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref="roomVersion" }
playservices-location = { group = "com.google.android.gms", name = "play-services-location", version.ref="locationService" }
maplibre-gl = { group = "org.maplibre.gl", name = "android-sdk", version.ref="mapLibreSdk" }
maplibre-anotation-plugin = { group = "org.maplibre.gl", name = "android-plugin-annotation-v9", version.ref="mapLibreAnotation" }
androidx-navigation = { group = "androidx.navigation", name="navigation-compose", version.ref="androidxNavigation" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref="materialIconsExtended" }
coil-compose = { group="io.coil-kt", name="coil-compose", version.ref="coilCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
mapsplaform-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref="gradleSecrets" }
